### ISSUE TITLE
How to handle authentication with react-static?

### ISSUE THREAD

**Issue by sedubois** [nozzle/react-static#106]
Thanks @tannerlinsley for open-sourcing your work, I just watched your talk :) You explain how static sites are super performant and aren't really limited to data that never changes, as any data change can trigger auto-redeploys and you can also query live data client-side (e.g with Apollo GraphQL).

However even if dynamic data isn't an issue, in the absence of an origin server, could you say what is your advice regarding pages which require user access control, like most web apps do?

Thanks!

**Comment by D1no** [comment]
React-Static behaves like a usual react app. Which is just front end. If content is private, there needs to be some Auth checking. We for example, use Firebase Hosting for the static part and the Firebase JS SDK for everything regarding non public with authentification. Just like a normal client side app.

https://firebase.google.com/docs/hosting/

**Comment by D1no** [comment]
And regarding live data, static content is for SEO and initial page load. If your content updates so quickly, you can have your CI build your website and deploy it every half an hour. As soon users access the site, they contact (normal react app) the same endpoint with the real-time data. React would automatically update the page based of the static pre-load. And that only happens really ones, since all the js is cached for recurring users and a single page for users who interact.

So it’s rather a question if you need to provide static content in real time to google or people without JavaScript. If that is the case, than you might just run a node.js Server with Express that serves HTML on a request basis.

**Comment by sedubois** [comment]
My content doesn’t update quickly, but I do have various pages which are subscription-only. So I wonder what to do for those. I’d much rather avoid having a server if I can avoid it. 

I don’t plan to use Firebase but instead a GraphQL backend where needed, probably the newly open sourced Graphcool framework.

Anyway I guess the only solution is to load any private data in componentDidMount instead of pre rendering it, meaning that I lose the performance benefit of static rendering for those pages. 

Considering that @tannerlinsley insisted so much in performance in his talk I thought he might have some precise ideas to solve this dilemma.

Another idea could be CloudFlare service workers which would allow to check auth at the CDN edge. Or Netlify also has access control but it’s just super expensive.

**Comment by tannerlinsley** [comment]
So IMO, I think you won't be able to static render auth-only pages without considering some other things/questions:

- If you statically render an auth-only page, it will be publicly available, since it's just an HTML.
- Does google really need to know about these pages? If it's subscription only, it's likely you could simpy render a placeholder that describes the content for SEO and for your users, then require a login.
- If the content is small enough, and not changing that often, you could easily embed the full content in your app, but choose not to display it until runtime, AFTER a user has authed (you could use some serverless auth like firebase or https://auth0.com/)

**Comment by sedubois** [comment]
Okay thanks. Basically I wanted to check my logic and see whether the fact that I have subscription-only pages meant that I should avoid a static rendering system and go for something like Next.js instead.

But looks like I can stop worrying about the matter so much and just load the data after having done client-side auth. As you mentioned I don’t care much right now about SEO for those pages.

Thanks a lot for your time :)
