### ISSUE TITLE
[Bug] TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by byte-artisan** [nozzle/react-static#1070]
### Reporting a bug?
I got the following error when try to build blank template:
 
ERROR in C:/Users/casi2/Projectos/site/empty/artifacts/react-static-templates.js
Module build failed (from ./babel-loader/lib/index.js):
TypeError: Cannot read property 'replace' of undefined

### Environment

`npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers` 

```
npx: installed 1 in 3.308s

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 6.77 GB / 15.88 GB
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
    Internet Explorer: 11.0.17763.1
  npmPackages:
    react: ^16.8.1 => 16.8.4
    react-dom: ^16.8.1 => 16.8.4
    react-hot-loader: ^4.3.12 => 4.8.0
    react-static: ^6.0.18 => 6.3.6

```
I just fixed other build error due to missing acorn module, using solution described [here ](https://github.com/nozzle/react-static/issues/1017)

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  react-static create test
2.  select blank
3.  cd test
4. build

### Expected Behavior

fresh new site

**Comment by byte-artisan** [comment]
It find out that running "react-static build" fails with this error.
But npm run build succeeds. 
Shouldn't work both ways?

**Comment by tannerlinsley** [comment]
This is likely because you have two different versions of React Static: one in your project and one as a globally installed module. Make sure they are both up to date. This is something we will make sure is not a problem in future versions.

**Comment by tannerlinsley** [comment]
v7 guards against having multiple or different copies of React now. Pleases reopen if you experience issues with it!

**Comment by Burnett2k** [comment]
What is the best practice here? If we already have a site created, then I guess we no longer need the globally installed version of react-static?  I'm seeing a lot of inconsistencies between running the dev server with no problems and then production builds fail.  Do you have any recommendations on how to make the dev and prod builds more similar so that I notice these failures earlier? It can be quite frustrating to think you are feature complete to then have your prod build fail for some unknown reason.

**Comment by tannerlinsley** [comment]
- When possible, use `npm` scripts to run react-static commands like `npm run build` which then runs  `react-static build`. This will ensure that your project's copy of react-static is used and not the global CLI
- If you choose to run `react-static build` manually in your CLI, make sure your global CLI is up to date. This is also important for creating new projects using the CLI.
- Most of the inconsistencies out of your control have been found and fixed with v7
- Any other inconsistencies between dev and prod are likely going to be the cause of node/browser environment confusion or things like CSS-in-JS / entity extraction during export. As long as you are [writing universal, node-safe code](https://github.com/nozzle/react-static/blob/master/docs/concepts.md#writing-universal-node-safe-code), you will avoid a large portion of inconsistencies. Along with using the right plugins for things like CSS-in-JS libraries, you'll be able to achieve near perfect functionality between the two (the exception being a few development-only async delays)
