### ISSUE TITLE
Question: What would be the preferred way to plugin an obfuscator?

### ISSUE THREAD

**Issue by neilyoung** [nozzle/react-static#1071]
So far I tried this:

- created blank project
- added obfuscator-loader as dev dependency (https://github.com/javascript-obfuscator/obfuscator-loader)
- created a node.api.js with the following content

```
export default pluginOptions => ({
  webpack: (config, { defaultLoaders }) => {
    config.module.rules = [{
      oneOf: [
        defaultLoaders.jsLoader,
        defaultLoaders.jsLoaderExt,
        defaultLoaders.cssLoader,
        defaultLoaders.fileLoader,
      ]
    }]
    return config
  }
})
```

AFAIK this node.api.js wouldn't change anything. What am I supposed to configure in order to have the .js files obfuscated?

TIA any help appreciated

**Comment by neilyoung** [comment]
OK, got better results by replacing the a.m. modules by this

https://github.com/javascript-obfuscator/webpack-obfuscator

The node.api.js is now

```
import JavaScriptObfuscator from 'webpack-obfuscator'

export default pluginOptions => ({
  webpack: config => {
    config.plugins.push(new JavaScriptObfuscator({
      rotateUnicodeArray: true, 
      sourceMap: false,
    }))
    return config
  },
})

```

During the `yarn build` I'm getting

``
 Error: (node:22323) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
````
...whatever this means.

At least the output is pretty much unreadable.

**Comment by neilyoung** [comment]
well thanks for nothing

**Comment by tannerlinsley** [comment]
I'm sorry we weren't able to figure this out with you yet. If you'd like to reopen we will gladly keep this on our radar. Keep in mind everyone here donates their time to each other free of charge with only the request that you respect their time in return.

**Comment by neilyoung** [comment]
@tannerlinsley Tanner, I'm sorry. Wasn't my best day yesterday. I don't wanted to be rude. I really appreciate your work and I love your project. Sorry again

**Comment by neilyoung** [comment]
Hi Tanner,

I'm in a catch 22 with react-static. Please take this notes as a personal opinion of a stupid user.

I'm having several incompatibility issues with react-static. I'm using this tool now since a year or so and didn't have such issues up to now. It is sad to see, that you are (as everybody in this world seemingly) are heading ahead towards yet another shiny new version and nobody looks back and tries to keep compatibility or at least don't break everything.

The time I started must have been around 4.6.x, now I'm at 5.9.12 and 6.3.6 breaks it. I'm reading you are going for 7. Don't get me wrong: I like your work and the results which can be achieve with it. But I'm just an ordinary user. I'm not "in" all these things, which make your daily work. For me this is just yet another tool I'm using from time to time. And I expect it to work, even if I'm having not used it since months. Maybe this is old school, but that's me.

Out of the sudden after a completely unrelated but necessary update(after a HD crash) I had to cope with the fact, that my projects did contain sourceMaps and by that pretty much readable quasi original code was deployed to the web server. I could fix that by your help and contributed, but I can't still find my contribution in the official package.  Not sure why.

I was trying to update to 6.3.6 just to see, that `npm` cannot longer be used to make a release build https://github.com/nozzle/react-static/issues/1053

OK why not heading to yarn, even though it is supposed to be outperformed again by npm?

Creating a fresh project, initial yarn install takes years, ok `yarn build` works at least, still the sourceMaps there, but I know the screws now.

Now going to add obfuscation. This might seem ridiculous in an Open Source world, but in some other worlds there is something like intellectual property which should be kept or for which it should be made at least harder to just pick the cherries and go away.

Trying to add `webpack-obfuscator` with `yarn` gives the error, that the package is incompatible with platform darwin (??) - interestingly npm has no problem to add that.

So now I'm standing here: Unable to add obfuscation to my project, because npm, which would allow me to add that, doesn't work with the latest 6.3.6, because the entire configuration of webpack seems to have moved from static-config.json to a new, obscure node.api.js...

I'm here and everything explodes out of the sudden. Please don't feel offended, but please keep a look back and don't jump on every new train while you are driving this forward. Try to keep at least a minimum backward compatibility. Not everybody is able to follow you that fast.

Thanks

**Comment by neilyoung** [comment]
But in case somebody is interested in combining react-static with webpack-obfuscation:

1) use react-static 5 `npm install -g react-static@5.9.12`. Use `npm install`, not `yarn install`
2) `npm install --save-dev webpack-obfuscator`
3) one time patch `node_modules/react-static/lib/static/webpack/webpack.config.prod.js` and replace any appearances of `sourceMap:xxx` by `sourceMap:false`. Should only be one.
4) have this static.config.json

```
import JavaScriptObfuscator from 'webpack-obfuscator'

export default {

  webpack: (config, { stage }) => {
    if (stage === 'prod') {
      config.performance = {
        maxEntrypointSize: 512000,
        maxAssetSize: 512000
      }
      config.stats = {
        warnings: false
      }
      config.plugins.push(new JavaScriptObfuscator({
        rotateUnicodeArray: true,
        sourceMap: false
      }))
   
      return config

    }
    else {
      return config
    }

  }
}

```
5) `npm run build` and ok
6) don't touch this again :)

**Comment by tannerlinsley** [comment]
Thanks for your input. I really do value it. To address some of your specific concerns:

- The sourcemap bug was a regression and I appreciate your help in fixing it. Those changes to master have not yet been released.
- Yarn is used in this project because of its workspaces feature and compatibility with Lerna. Both allow us to develop the core library and plugins using the same dependencies and perform batch releases that stay in sync. Any NPM specific bugs are unfortunate and in the future, we hope to have tests for those edge cases. Up to this point, we are not aware of any large bugs caused by using NPM other than #1027.
- Obfuscation: While I'm sure it's possible with some amount of work extending the webpack configuration, I'm not entirely sure how React Static will behave with it in production. I personally have always placed code deemed "intellectual property" behind a server and never on the client. Even good  obfuscation can sometimes be unravelled or understood. I would be more concerned about the code behaving the way it should or running into unintended side effects in production because of it. If you can get it to work, then awesome! But proceed with caution, as it is not something I plan on supporting out of the box with React Static.
- Stability: I assure you my first priority for React Static is stability. We release features and bug fixes with as much backwards compatibility as possible, but unfortunately breaking changes must happen from time to time to fix underlying architectural issues. These breaking changes **do not** signify that a previous major version is feature complete or stable. They merely follow semver so as to not break minor and patch update expectations. You are correct that I am working on v7 right now, and yes, it will introduce breaking changes. These changes are likewise going to contribute the most stable version of React Static to date. 

Lastly:
> But I'm just an ordinary user. I'm not "in" all these things, which make your daily work. For me this is just yet another tool I'm using from time to time. And I expect it to work, even if I'm having not used it since months.

Open source software is not my full-time job. I co-own a successful startup and proudly sucks up most of my time and any of my remaining free time is usually spent with my family. I **occasionally** work on my open source software, so when I do I prefer to move fast, waste no time, and get things done.

**Comment by neilyoung** [comment]
Hi Tanner,

thanks for your thoughts. Appreciated.

> I personally have always placed code deemed "intellectual property" behind a server and never on the client. 
Sure. The same here. I'm aware of all the dangers of re-engineering. Doing this too, sometimes :) 
That being said: Of course, there is nothing in my code, what I would not be willing to give away, no secrets, nothing. It is just that I would not hand that out for absolutely free. If one makes it and reverse engineers deeply obfuscated stuff, then he has deserved it and I give it with a smile. But there is a little difference between "deploying sourcemaps" and "obfuscation".

Anyway. This is solved. The obfuscation works great and I don't see a major problem to use it for me in my projects.

 
> we are not aware of any large bugs caused by using NPM other than #1027.

In fact there is this https://github.com/nozzle/react-static/issues/1070

Easy to reproduce: Create a blank project with 6.3.6, `npm install`, `npm run build` Impossible

Thanks for your work. Don't feel offended. I'm generally happy and after having now spent some hours I'm back on track and have a good setup with 5.7.12. 6.3.6 does not work for me, because npm does not work. Using npm 6.4.1

**Comment by tannerlinsley** [comment]
>  But there is a little difference between "deploying sourcemaps" and "obfuscation".
Again, this was a regression and is not by design. We are well aware of the differences, and I'm glad you got obfuscation working in your project.

My only advice would be to use yarn if you want to take advantage of the latest version. NPM clearly is having some resolution issues, so I cannot recommend using it until those are fixed.

**Comment by neilyoung** [comment]
Hehe.. Yarn has surprisingly the problem to be unable to ´yarn add dev webpack-obfuscator` After a while it complains about not being able to support platform darwin withi this or so... NPM installs the plugin w/o problem. :)

**Comment by tannerlinsley** [comment]
You mean `yarn add webpack-obfuscator --dev`?

**Comment by neilyoung** [comment]
Hmm. Did I made a mistake in yarn command line? Let me check that... Impossible is nothing...

**Comment by neilyoung** [comment]
Good that we talk about. After having issued the correct yarn command it works.

What I have done:

`npm install -g react-static@latest`

```
react-static -V
6.3.6
react-static create  // blank project chosen
yarn build    // ok so far
yarn add --dev webpack-obfuscator    // works. Shame on me
```

Then I added a `node.api.js` with the following content:

```
import JavaScriptObfuscator from 'webpack-obfuscator'

export default pluginOptions => ({
 webpack: (config, { stage }) => {
    if (stage === 'prod') {
      config.performance = {
        maxEntrypointSize: 512000,
        maxAssetSize: 512000
      }
      config.stats = {
        warnings: false
      }
      config.plugins.push(new JavaScriptObfuscator({
        rotateUnicodeArray: true,
        sourceMap: false
      }))
    }
    
    return config
  }
})

```

During `yarn build` this "error" kicks in, but it just seems to be a warning:

```
=> Bundling App...
  Error: (node:54810) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

and a couple of useless warnings (which seem to be a webpack issue) appear

`WARNING in templates/styles.b7475607.js contains invalid source map
`

Anyway: The result is fine.

Thanks
