### ISSUE TITLE
Dynamic Routes

### ISSUE THREAD

**Issue by tujoworker** [nozzle/react-static#111]
I know, this is probably a stupid feature request 😝 Specially as this little cool "framework" uses static in the name.

But I think this could be a nice little, but powerful addition. I think of small route pages witch don't have to be a static site with content. Maybe even just a *info popup or overlay* thing, witch goes over an existing content - but triggered by the router. I was into a case like that recently. 

I made a little [demo / test case](https://github.com/tujoworker/react-static-dynamic) (with a simple dynamic route). And it looks promising. The only two tings are (running the **build** sources):

- A config addition, maybe in the **static.config.js**, like *dynamicRoutes()* ore even in the *getRoutes* config like *ignoreExport: true*. Then we would not get a 404 on the **/dynamic/routeData.json** file lookup.
- Once we refresh / reload the page, the CSS gets not assigned. That happens as the css classes are not anymore defined in the HTML. Maybe only a CSS Modules issue.

In many ways, react-static is a nice starter-kit with much power, and can easily compete with many of the top rated projects on this site: www.javascriptstuff.com/react-starter-projects

**Comment by tannerlinsley** [comment]
So if I understand what you're saying, you want to use React-Static as a replacement for a non-static react app, eg create-react-app?

**Comment by mjsisley** [comment]
react-static looks like it could serve as a replacement for create-react-app for non-static sites with a few tweaks. I would want to use it in that way if possible.

I think pre-rendering as much as possible on a non-static react app is still be beneficial. Maybe certain components depend on dynamic content, but the majority of the site doesn't. Or maybe just a shell is static. Maybe some routes should be static and some not.

You can prerender an app made w/ `create-react-app` w/ `react-snapshot` or `react-snap`, but I have had trouble using this out of the box.

An option to `ignoreExport` at the route level. Or maybe a component/HOC that could be used to tell `react-static` that a certain portion of the site shouldn't be prerendered (I haven't looked at react-static internals, but maybe that means wrapping something like: https://github.com/kadirahq/react-no-ssr). Or both.

I think it would be awesome if `react-static` supported these use cases.

**Comment by tannerlinsley** [comment]
I'll start working on this then. Great input!

**Comment by mjsisley** [comment]
I would also like to point to the discussion at https://github.com/zeit/next.js/pull/1576. 

NextJS ended up not taking the PR and went in a different direction. But there are ideas here worth noting (ie, having some props available at build time on a route (markdown files, json data, maybe data from a CMS like contentful) and then other props that should come dynamically).

**Comment by tujoworker** [comment]
@mjsisley Thanks for clarifying and great summary!

**Comment by tannerlinsley** [comment]
So this is actually quite easy to handle.  But there are a few things to handle first.  Currently when you navigate to an endpoint that is not a static exported route, you see a flash of 404 before react mounts. How should we fix this?

**Comment by mjsisley** [comment]
My thoughts on possible solutions:

Instead of flashing 404, maybe a placeholder statically rendered page could be flashed (probably best to leave config at the route level, maybe something like: `{ ..., ignoreExport: true, staticPlaceholder: StaticPlaceholderComponent }`. Could also maybe have a default for all pages available. 

If using an HOC (or maybe just a wrapping component) to block prerendering of any arbitrary portion of the tree, the route would still be set statically. But maybe having a `staticPlaceholder` prop on that HOC/wrapping component would be helpful... so a placeholder component can be statically prerendered... and then replaced when React mounts with the components that should only be used dynamically.

`staticPlaceholder` may not be the best name, that may require some more thought.

**Comment by tannerlinsley** [comment]
Let me take it to the next level. Imagine there is no route registered at
all for this endpoint. I think this could be a server level requirement.
Normally with a react app you want every uel to redirect the index.html
file so react can handle it. In this case, index.html is not blank. I think
a possible solution here would be to render the root 404 page as a loading
spinner of sorts. This would ensure that when a route is not recognized at
the server level, it is sent to the 404 page, which loads, then uses
internal routing to determine what to show.

**Comment by derekperkins** [comment]
I think this would be great, as long as it doesn't impact the ease of use on the static side. I think all the defaults should be based on the needs of a purely static marketing site, including the 404, with dynamic setups requiring config overrides.

**Comment by tujoworker** [comment]
I think the great thing about React is, that it is a library, and this forces so many to make frameworks.
Zeit.js gains a huge popularity. But the question is why? I think, react-static has no many benefits unlike SSR, that it's just a question of time that frameworks like *react-static* will gain a huge popularity. Developers will make all kinds of stuff with tools like this one 🙀 - I think.

**Comment by tannerlinsley** [comment]
Alright, I just released a patch that should get rid of any 404's you encounter when loading non-statically-exported routes. I think this is a good time and place to just see what happens.  Given that error, there really isn't anything stopping you from using react-static as is as a replacement for create-react-app.  I am already doing that myself on a few projects. Closing this issue for now, but we can keep discussing here.

**Comment by mjsisley** [comment]
@tannerlinsley So you are suggesting using the first load 404 page as a loading screen, and only serve a true 404 page from react? This was actually my first thought too, but didn't suggest because it feels a little "hacky" to hijack the server 404 page. Maybe that is fine though... every case should be handled (as long as javascript is enabled). Having the option to have each route to have their own placeholder adds some flexibility though, as each dynamic route could have its own shell. But both could be included.

@derekperkins raises another issue with this method, that going this route would alter 404 behavior for purely static sites (though it could be a loading screen that times out to a 404). Maybe just adding something like `enableDynamicRoutes: true` to the config to swap in this behavior would work though.

@tujoworker Agreed! React is great. A flexible high level prerendering framework like this one.

**Comment by mjsisley** [comment]
@tannerlinsley Sounds great! Will take a look soon and bring any issues (if there are any) up here. Thanks!

**Comment by tannerlinsley** [comment]
That may be true, but for now, I'm really trying to avoid any changes to the api to satisfy this use-case. I think we should try our hardest to make things work with the existing api first, then as we discover the full repercussions of the use case, we can determine if more needs to be done. :)

**Comment by tujoworker** [comment]
I updated my [test case](https://github.com/tujoworker/react-static-dynamic) with the latest 4.0.1 version and tested out the *static.config.js* `is404: true` setting. Things did not work as expected. I can't se the effect on setting the `is404: true` component anywhere anytime. But the `<Route component={NotFound} />` in *App.js* gets exported.

So, once I disable JavaScript, I se the 404 page once we visit */dynamic*.
I expected that the is404 component will show up there, right?
