### ISSUE TITLE
[Bug] Routes component’s getComponentForPath prop removed?

### ISSUE THREAD

**Issue by Cinamonas** [nozzle/react-static#1118]
The removal of `getComponentForPath` was not mentioned in the changelog and I can no longer find it in the source code of V7.

[Animated Routes example](https://github.com/nozzle/react-static/blob/67e6d0e0aea568412b10258381d0af57623051fe/docs/guides/animated-routes.md) is still using it, so it’s probably no longer working.

It would be good to amend the changelog and mention this breaking change.

**Comment by tannerlinsley** [comment]
I've updated the changelog to state this change. I'm also working on a new example for the animated routes example. Thanks!

**Comment by buzinas** [comment]
> I'm also working on a new example for the animated routes example.

Any news?

**Comment by wappsify** [comment]
If anybody has gotten them to work, I would also appreciate a nudge in the right direction regarding how to implement animated routes with react-static v7!

**Comment by simonunlikely** [comment]
Any news regarding the new example in the docs ? Trying to implement animated routes transitions with v7 but so far no luck !

**Comment by wappsify** [comment]
Hey @simonunlikely et al.,
we have since figured out a way to implement animated routes with react-static v7. However we have switched to use `react-static-plugin-react-router` instead of the `reach-router` one that comes with the `basic` template of react-static.

We implemented the page transitions with `react-spring`, however you can use your preferred animation library.

You can find a working minimal example here:
https://github.com/wappsify/react-static-v7-animated-routes

Clone the repo, run `yarn` to install the dependencies, then `yarn start` to start it.

I hope this helps!

**Comment by sw-yx** [comment]
great answer :) linking to this for future docs update

**Comment by simonunlikely** [comment]
Thanks for the great example! We managed to implement something with reach router, we were just missing the `routePath` bit to pass to the `Routes` components. Don't remember the docs mentioning anything about this by the way? Could be worth adding a few words about its use cases?

**Comment by SleeplessByte** [comment]
`reach-router` example using #1181 was listed here: https://github.com/nozzle/react-static/issues/1162#issuecomment-492302334
