### ISSUE TITLE
FOUC using the SASS plugin

### ISSUE THREAD

**Issue by virtualstyle** [nozzle/react-static#1177]
I'm not using styled components. I'm using the SASS plugin. Some minor tweaks to the webpack config. On dev (yarn start), the loading component shows nicely, all good. On build, staging or prod, never see a loading indicator, get unstyled content that rapidly moves around as my styles are applied.

Google searches aren't turning up much, there's the router.subscribe method, which seems to be very old, then something about a Loading hoc, but nothing I can get working. About to give up on the package... what's up with simple loading handling on build rather than dev server?

**Comment by sw-yx** [comment]
hmm. check the generated html is loading correctly. the sass plugin is really simple - if youre familiar with the webpack loader: https://github.com/nozzle/react-static/blob/57ecc92a63182aab91112be5c3e787c338308b09/packages/react-static-plugin-sass/src/node.api.js#L23-L38 PR's welcome to fix though but i think @tannerlinsley uses this actively

**Comment by virtualstyle** [comment]
Well, everything loads correctly eventually, because the site/app is working. The problem is an FOUC, which doesn't happen on dev. So the sass plugin must indeed be getting me my compiled CSS. But I'm NOT getting to see a loading indicator while it does so, I get unstyled content, which jumps around all crazy while css loads and is applied. Never see a flash of my loading component. But all the code loads fine, site works fine. The problem is FOUC.

**Comment by sw-yx** [comment]
sorry, i got nothing 😐 i use the styled components one myself.

**Comment by silvenon** [comment]
@virtualstyle do you have a repo I could try?

**Comment by virtualstyle** [comment]
No repo, new project. I'm going with https://github.com/markdalgleish/static-site-generator-webpack-plugin, I like getting my webpack.config back in my hands.

**Comment by Reggino** [comment]
I'm running into the same issue. I think this should be re-opened

**Comment by sw-yx** [comment]
@Reggino have a repro?

**Comment by Reggino** [comment]
I'll try to setup a demo in a stand-alone repo.

But it seems to be reproducible by disabling Javascript in the browser and then opening a built page: the '.scss' file loaded in the used modules don't seem to embedded in the intially loaded css file.

**Comment by Reggino** [comment]
Reproduction is pretty straightforward:

- Scaffold a fresh app
- Add `sass-plugin`
- Load sass file in page
- Build it.

This setup can be found (here)[https://github.com/Reggino/react-static-issue-1177]

When you open the built page in your browser __without javascript disabled__ you'll notice the missing CSS from the sass-file that should be loaded for that specific page. This is because that .css chunk is loaded by JavaScript after the initial render. The sass module is missing a tiny but crucial piece of configuration that makes Webpack create a single big chunk of CSS (like in the regular css module)

I've created a (PR)[https://github.com/nozzle/react-static/pull/1249].  to fix that.
