### ISSUE TITLE
[Bug] React Static does not generate static content if basePath is specified

### ISSUE THREAD

**Issue by JoseFMP** [nozzle/react-static#1182]
When setting the `basePath` either in production as `basePath` or `stagingBasePath` for staging environment, React static does not generate static content any more.

Everything keeps working fine, and the base paths are applied correctly. However, the HTML content is not generated statically anymore. It is only rendered dynamically. I.e. the HTML files generated do not contain the HTML pre-rendered content but only references to client-side scripts that will render the content upon loading the page in a competent browser. Which is exactly not the point of a static content generator.

The rest works fine

### Environment
NodeJS: 10.x any version seems affected
React static: 7.0.X any version seems affected
```
System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 11.41 GB / 31.12 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.4
  npmPackages:
    react: ^16.8.2 => 16.8.6 
    react-dom: ^16.8.2 => 16.8.6 
    react-redux: ^7.0.2 => 7.0.2 
    react-static: 7.0.10 => 7.0.10 
    react-static-plugin-reach-router: ^7.0.0 => 7.0.0 
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0 
    react-static-plugin-typescript: 7.0.10 => 7.0.10 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-static: 7.0.7
```

# Steps to reproduce: 
* Set-up a NodeJS environment
* Install `react-static` npm package
* Use react-static CLI to generate the boilerplate project by issuing `react-static create`
* In the configuration, add the property `basePath: 'example'`
* Run `reac-static build` to build the static content
* Go to the dist folder and inspect the HTML files.

### Result
Find out no HTML tags are rendered, instead only client-side scripts are loaded.

### Expected behavior 
The HTML tags of the React components that render the UI are present in the HTML file. I.e. the static content is generated statically.

## Important notes
* Please, note that, by just removing the `basePath` property in the react-static configuration, the HTML content is generated statically flawlessly.

* Also, note that this affects equally production and staging environments. I.e. by setting `stagingBasePath` and making an staging build, the problem also appears in the staging build. Independently of whether `basePath` is set or not. If `basePath` is set, then the prod build will no have the HTML tags of the page rendered statically, independently of what's happening with the staging build.

* Although the HTML tags of the page to render are not present, the client side imported scripts do generate the HTML tags correctly dynamically.

**Comment by marqpdx** [comment]
I confirm that i got this same behaviour. Neither Stage nor Live can be built. No HTML files.

**Comment by JoseFMP** [comment]
@marqpdx  is it the same bug? In my case the HTML files get created, however they do not have HTML tags with the UI pre-rendered.
Instead just import client-side scripts to generate the UI when loading the page in the browser.

**Comment by JoseFMP** [comment]
@gbrsales do you know if PR #1196 might fix also this issue?

**Comment by nddery** [comment]
#1196 didn't solve it for us, but, it might be related. I think the issues is either in the `staticInfo` or in the Reach router plugin (could also be in the [React router plugin])https://github.com/nozzle/react-static/blob/master/packages/react-static-plugin-react-router/src/browser.api.js#L23) - although it doesn't make the path absolute there).

Reach route specifically makes the location URL absolute - meaning that given a `staticInfo.path` of `blog/post/79`, it'll transform it to `/blog/post/79` - which is outside of our app, hence rendering nothing.

Seems like keeping the URL relative in the router doesn't work (because it is outside of the main router, which has the base path ?).

I am not sure if the fix should be in React Static or in the Reach Router plugin - ie.: should `staticInfo.path` already contain the `basePath` (but not the `siteRoot`, so not `REACT_STATIC_PUBLIC_PATH`), or should it be added by the Reach Router plugin ? Happy to open a PR with either of the solution!
