### ISSUE TITLE
Need replace html string text from react component

### ISSUE THREAD

**Issue by avneesh30** [nozzle/react-static#1205]
Issue : - we are facing the shortcode issue. we use shortcode {{email}} for email subscription in content and the server provides content as HTML string on the frontend side. we render string to HTML on the frontend side from dengerouslySetInnerHTML react function..

Example : -` let description = '<p>contect here {{email}} content here {{email}} content here</p>'`;

we use react dengerouslySetInnerHTML function that convert HTML string to actual HTML. 
`<div dangerouslySetInnerHTML={{ __html: description }} ></div>`

I'm doing - replacing {{email}} text from react email component but we are not able to insert react component in the string.

Like -  `description.replace('{{email}}', <EmailComponent />)`

**Comment by sw-yx** [comment]
hmm. how do you normally do this in something like create-react-app or gatsby?

**Comment by Pixelatex** [comment]
Closing this is because this is not related to RS at all.

About your issue, you can't use the replace function because that will insert strings, not components. + react components placed inside the 'dangerouslySetInnerHtml' function will not work as they are not compiled correctly.

The way you are doing it is dodgy at best... + will cause a ton of issues in regards to webpack compilation, code splitting, etc..

If you want the server to decide what content is shown on the frontend, use configs.

server returns a json object,
 e.g.
```json
[
{ "element":"paragraph", "content":"this is paragraph content"},
{ "element":"emailcomponent"}
]
```

And loop over that array and return the react component or html element in your render function.
Beware that this is not an easy way to create a react app, I'm not going to explain in detail how this will work as it is very project-specific. Consider not serving content from the server if possible if you're unsure on how to make this work otherwise.
