### ISSUE TITLE
[Bug] Build failure with React Hooks 

### ISSUE THREAD

**Issue by sw-yx** [nozzle/react-static#1215]
### Reporting a bug?

1. new RS project, from basic template
2. use `useState` hook in the default export component in `src/pages/index.js`
3. `yarn start`. observe no errors.
4. `yarn build` and get this error:

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

### Environment

Run and copy the result of:

`npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers` 

here:

```

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 118.99 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 74.0.3729.169
    Safari: 12.1
  npmPackages:
    react: ^16.8.1 => 16.8.6 
    react-dom: ^16.8.1 => 16.8.6 
    react-hot-loader: ^4.3.12 => 4.6.3 
    react-static: ^6.0.18 => 6.1.5 
  npmGlobalPackages:
    react-static: 7.0.10
```

of course include any other package versions here if relevant. 

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

as above. i have put my code into a repo https://github.com/sw-yx/react-static-hooks-bug-repro

### Expected Behavior

it should just build

### Reproducible Demo

https://github.com/sw-yx/react-static-hooks-bug-repro

**Comment by wappsify** [comment]
Hooks are only supported since react-static version 7, I think? Even though I can see your globally installed react-static version is >=7, the project you initialized with the cli (presumably with `react-static create`?) uses an older version of `react-static`:

https://github.com/sw-yx/react-static-hooks-bug-repro/blob/4daf0e68ece72dc532164218e101730789ee6a46/package.json#L18

I tried reproducing that bug, however for me when creating a new project with the `react-static create` command, the resulting project does use a more up-to-date version of react-static (`^7.0.0`).

You might want to try reinstalling react-static globally and then create a new project, see if that helps?

**Comment by sw-yx** [comment]
dohh. that is probably it. makes sense. i'm running it locally (symlinked from the git repo instead of npm install) based on the current master but have had weird version issues before. makes sense!
