### ISSUE TITLE
Comparison/differences with next.js static export

### ISSUE THREAD

**Issue by albinekb** [nozzle/react-static#14]
Nice project! Why should people choose this over using [Next static HTML export](https://github.com/zeit/next.js#static-html-export) ? Would it help with a comparison/differences in the readme? If you want I could write it and send a PR :)

**Comment by tannerlinsley** [comment]
I think it would be beneficial to have a section on the differences, though since they are conceptually different on some levels, I'm not sure a comparison table would do it justice. 

One of the main differences to next is that react-static behaves like a regular react app. So you don't build your pages using js files in a folder, you build them using react-router.

The other very large difference is that react-router only exports an HTML file and JSON file for each route, both of which are used at the most opportune moment (HTML for first-load, and JSON for subsequent navigation) for speed and low bandwidth. Next.js is much more bloated, since for every page, it exports an HTML file and . JS bundle containing all of the logic to render the root component. This results in a ton of duplicate code across pages.

Due to the bundle/page patter than next uses, it can become extremely slow to export pages, since webpack is running for every single page. React-static only exports a single bundle that won't grow in size with the amount of dynamic pages that you bring to the table. So exporting is extremely fast.

These are just a few examples. More of them are outlined in the introductory medium article I wrote.

**Comment by albinekb** [comment]
Ah, I missed that medium article. Thanks for explaining 👍  I think a section in the readme that outlines this, and links to the medium post or this issue would be 👌  for newcomers like me to understand. Thanks 🥇

**Comment by tannerlinsley** [comment]
I'll try and put something together this week :)

**Comment by purge** [comment]
i've just converted a complex next.js project to this (I dislike nexts href/to, getInitialProps ,slow page changes & build id hashing). I am very happy to report that all of these have been resolved using react-static and it's much more 'reacty'. The conversion was a doddle too.

**Comment by tannerlinsley** [comment]
Going to close this now as I believe the Article is sufficient for this purpose right now.

**Comment by divyenduz** [comment]
Would be good to link the medium article on this issue?

**Comment by tannerlinsley** [comment]
https://medium.com/@tannerlinsley/️-introducing-react-static-a-progressive-static-site-framework-for-react-3470d2a51ebc
