### ISSUE TITLE
Filechanges in /public in development?

### ISSUE THREAD

**Issue by pA1nD** [nozzle/react-static#141]
I have a css file in `/public`. If I change it while `react-static start`, the file is not being updated and the server still serves the old version. Essentially, I have to restart for every change in the css.

Is there a setting to change this? I could not find anything in the docs.

Thanks so much!

**Comment by EmilTholin** [comment]
Hi @pA1nD!

The `/public` folder is indeed not watched, and is just copied to the `/dist` folder. If you instead `import` your CSS into one of your JavaScript files, it will be hot reloaded in development and extracted properly for production:

```javascript
import React from 'react'
import { Router, Link } from 'react-static'
import Routes from 'react-static-routes'

import './app.css'

export default () => (
  <Router>
    <div>
      <nav>
        <Link to="/">Home</Link>
        <Link to="/about">About</Link>
        <Link to="/blog">Blog</Link>
      </nav>
      <div className="content">
        <Routes />
      </div>
    </div>
  </Router>
)
```

**Comment by gagan0723** [comment]
@EmilTholin It would be nice if we can show a warning if the user imports something(js or css) outside the src folder.

**Comment by tannerlinsley** [comment]
How are you importing this file?

**Comment by tujoworker** [comment]
Same thing applies to images and other static files. It would be really nice to **watch the public** folder as well. Then we can easily have a ton of images there, without every time "importing" them just to activate the [webpack loader](https://github.com/nozzle/react-static/issues/17#issuecomment-335537103).

```jsx
<img src="[Image is in public folder]/assets/logo.png" alt="logo" />
``` 
instead of:

```jsx
import logoImg from '[image is in src folder]/logo.png'
<img src={logoImg} alt="logo" />
``` 

Yes, You can do this today, but You have to restart webpack every time You add a new image.

**Comment by tannerlinsley** [comment]
Okay I'll add this in.
