### ISSUE TITLE
how to use routeProps in meta tags

### ISSUE THREAD

**Issue by rileylnapier** [nozzle/react-static#153]
hi, im trying to use react-static to render product data in an ecommerce setting.  so i am requesting product data via api in route-props.  i would like to use this data for meta tags. 

looking at site.config.Document ~ it looks like it has siteProps, but not routeProps

do i have access to routeProps here?

**Comment by EmilTholin** [comment]
Hi @rileylnapier!

`routeProps` in `site.config.Document` wouldn't really make much sense, since it's just a general template.

You can use the [Head](https://github.com/nozzle/react-static#head) component in one of your components, use the [getRouteProps HOC](https://github.com/nozzle/react-static#getroutepropscomponent) to get your route data, and change your meta tags there:

import { Head, getRouteProps } from 'react-static'

```javascript
export getRouteProps(() => (
  <div>
    <Head>
      <meta charSet="UTF-8" />
      <title>This is my page title!</title>
    </Head>
    <div>
      My page content...
    </div>
  </div>
))
```

**Comment by rileylnapier** [comment]
kk, ill play with this and let you know if i have questions
