### ISSUE TITLE
Support for / Routes for Proxy?

### ISSUE THREAD

**Issue by frewinchristopher** [nozzle/react-static#157]
Hi all,

I'm having trouble with a path on my site that I would like to proxy to a separate app, i.e. I have a tiny single page app running on port 9000 (not the same port as my static site), so I would like the path `/tiny-app` on my static site to forward to that port 9000:

`https://my-super-cool-site-built-with-react-static.com/tiny-app` --> `localhost:9000`

Unless I'm mistaken, something like proxying can't be done within `static.config.js`? So I've made attempts with my own server.js with this using express, i.e.:

// Serve static assets
`app.use(express.static('./dist')); // <-- the dist folder generated by react-static`

// proxy
```
app.all('/tiny-app*', function(req, res) {
   proxy.web(req, res, { target: 'http://127.0.0.1:9000' }); // southpark markov chain app
});
```

The problem is, the page breaks because somewhere the `/assets/app.js` file is still being requested - I would guess somewhere with react-static

So I suppose my question(s) are: 1. Is proxying/forwarding actually possible from localhost:9000 (or any localhost/ different endpoint for that matter), or am I best doing this sort of thing with my own server.js? and 2. With the proxy seemingly working (?), how can I prevent the /assets/app.js and other css/asset requests from going to the react-static assets?

This is probably a basic question, I'm sure someone with much more express and SSR experience can point me in the right direction.

**Comment by tannerlinsley** [comment]
Because react-static simply generates static content, you would need to do this on a server. React-static will soon support static redirects, but since there is no server being used (other than just serving static files), there is no opportunity to intercept or proxy a request to a certain endpoint to another without using some type of server.  If this is something you'd like to do, I would first double check that you couldn't do something similar by using a different sub-domain of sorts or if your use case is valid. If you end up still needing this functionality, I suggest investigating using something like express or nginx to proxy requests from that route to a different location. Be aware though, that sticking a server in front of a static site could potentially slow it's performance, depending on how it is implemented.

**Comment by knpwrs** [comment]
I am interested in this for serving a development build of `netlify-cms` from another webpack instance. The proxy is not required in production because `netlify-cms` is also built to static files.

The way I have things set up right now, `react-static` builds to `dist` and I have a separate webpack build for `netlify-cms` which builds to `dist/admin`. I would like the `react-static` server to proxy `/admin` to the `netlify-cms` dev server during development.

**Comment by tannerlinsley** [comment]
You can do this by extending the webpack dev server as you normally would
with webpack. https://react-static.js.org/docs/config/#devserver
