### ISSUE TITLE
siteRoot with path

### ISSUE THREAD

**Issue by bpierre** [nozzle/react-static#204]
It seems react-static doesn’t work for websites served from a path that is not `/`.

To reproduce:

1. Define siteRoot:

```js
// static.config.js
export default {
  siteRoot: 'http://localhost:5000/dist'
}
```

2. Run this:

```sh
npm run build && npx serve
```

3. Open <http://localhost:5000/dist/>

**Comment by tannerlinsley** [comment]
Is this still an issue?

**Comment by bpierre** [comment]
Yep

**Comment by marbemac** [comment]
An issue for us as well!

As a temporary measure, does anybody know how to customize the webpack config to place the generated app.js and app.css files in a subfolder, and make sure that the paths injected into the html files include the subfolder as well?

**Comment by bpierre** [comment]
@marbemac That’s what I tried at first, but the routing system also need to know about the site path, instead of assuming `/`.

**Comment by Jonarod** [comment]
@marbemac I don't know if it helps, but I solved a similar issue on another framework using `copy-webpack-plugin`. Something like:

`npm install --save-dev copy-webpack-plugin`

then
```js
import CopyWebpackPlugin from 'copy-webpack-plugin'

export default {
  webpack: (config) => {
    config.plugins.push(new CopyWebpackPlugin([{ context: `${__dirname}/src/`, from: `app.*`, to: `/absolute/path` }]) )
    return config
  }
}
```
Theoretically this should move all files starting with `app.` to `/absolute/path` in the output build folder, so AFTER build, files should be at `/build/absolute/path/app.js`...

I didn't test it, but I used it several times and it works, now you may tweak `from`, `context` and `to` to suit you.

I don't need this functionality so far, but just a thought I had to help solving the issue :)

**Comment by marbemac** [comment]
@Jonarod a good idea, but only half of the solution :). All of the script/style tags in the generated HTML files will still be pointing to the root /app.xxx.js /style.xxx.css files. The written js and css files need to also point to the new file paths - would this accomplish that (haven't had a chance to try it yet)?

**Comment by Jonarod** [comment]
I see.
I was suggesting this based on :
> As a temporary measure, does anybody know how to customize the webpack config to place the generated app.js and app.css files in a subfolder...

Now, I am curious as to what should be displayed at `example.com/` if `siteRoot` is `example.com/dist` ?

**I may be wrong**, but it seems to me that everything is relative...
Say within any component, you have a link like `<a href="/my-post">My Post<a/>`. Should this link be automatically re-mapped to `<a href="/prefix/my-post">My Post<a/>` according to you ? If that is, what if you really meant to point to `example.com/my-post` ?

That being said, would move ALL `/dist` content into a nested `/dist/prefix` folder solve the issue ?
If yes, you can do it tweaking `copy-webpack-plugin`'s `from/to`.

Now, this trick will eventually mess up all dev mode :(

**Comment by Jonarod** [comment]
In addition to my answer, please have a look at this webpack option : [publicPath](https://webpack.js.org/configuration/output/#output-publicpath)

Hope it helps :)

**Comment by bpierre** [comment]
.

**Comment by mcchin** [comment]
Updating webpack config with publicPath and copy-webpack-plugin doesn't work. I think as @bpierre mentioned the dist is always assuming /. 

Maybe there is another work around, but I couldn't get react-static to work on other sub path besides root.

**Comment by loganpowell** [comment]
Got to this thread by Google'ing "Warning: No 'siteRoot' defined in 'static.config.js'!"

my error:

```
 yarn build
yarn build v0.22.0
$ react-static build

=> Copying public directory...
=> [✓] Public directory copied: 97.633ms
=> Building Routes...
=> [✓] Routes Built: 173.473ms
=> Bundling App...
=> [✓] App Bundled: 20727.769ms
=> Exporting Routes...

      => Warning: No 'siteRoot' defined in 'static.config.js'!
      => This is required for both absolute url's and a sitemap.xml to be exported.

=> [✓] Routes Exported: 4167.718ms
=> Site is ready for production!: 25171.865ms
Done in 28.17s.
```

Not sure if I should be concerned about this as this issue seems stale...

**Comment by loganpowell** [comment]
Still banging my head on this one. I did get the `dist` folder to act as my gh-pages branch and it rendered on github pages, but my [iconfonts](https://github.com/loganpowell/census-academy/tree/master/dist/iconfont) and [`typeface` packages](https://github.com/KyleAMathews/typefaces/tree/master/packages) don't seem to be working. My gh-pages site shows a bunch of boxes instead of icons and flickers every time I click on a link. 

I reverted to serving github pages from a full branch, but that [doesn't work](https://loganpowell.github.io/census-academy/dist/) either.

Anyone come up with a way to serve `react-static`? I can't find any documentation on best practices for github or any other static site service (e.g. Netlify, surge) anywhere :(

**Comment by stychu** [comment]
@loganpowell I had the same problem as you have. The solution for this is to add `siteRoot: 'https://xyz.github.io/repoName/'` to you `static.config.js` so it will serve routes as /repoName/route and its working. Still looking for importing imgs because they dont load on gh-pages but on local they does.
Also I've noticed some weird behaviour with gh-pages. Sometimes when I do push new changes do gh-pages branch it preserves the old data and i need to clear cache so it can load the new pushed changes this is super annoying. Anyone had some problem with this ?

**Comment by cliffasaurus** [comment]
@stychu i'm not sure if our problems are exactly the same but mine goes like this:
i declare siteRoot: https://myserver/projects/mysite
with my assets at https://myserver/projects/mysite/assets/images/img.jpg
images don't load and they seem to be asking for https://myserver/assets/images/img.jpg -> 404

**as for gh-pages caching they have a max-age setting of 10 minutes so the browser won't check for 10 minutes since last retrieval (unless you clear the cache on your own, like you do)

**Comment by stychu** [comment]
@cliffasaurus I had problem with loading the images but i solved it by moving my assets to the public directory and setting src for image with `./` prefix
```
import React from 'react';
import { getSiteProps } from 'react-static';

import logoImg from '../../public/logo.png';

export default getSiteProps(() => (
    <div>
        <h1 style={{ textAlign: 'center' }}>Welcome to</h1>
        <img src={'./'+logoImg} alt="" />
    </div>
));
```
![image](https://user-images.githubusercontent.com/9383657/34780379-494edd8c-f623-11e7-9efc-b153ff1f6003.png)

**Comment by tannerlinsley** [comment]
Looks like we need to adjust the webpack path in prod to account for the
siteRoot. Thoughts?

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version. All prefixing now uses the final webpack `publicPath` :)

**Comment by cliffasaurus** [comment]
Thank you so much for this!!!

**Comment by andywarren** [comment]
I'm not sure I understand this, but I just installed React-Static and created a site using the Sass template via NPM. When I ran the build command I got the static files and uploaded them all to the server into a specific directory, but the site doesn't work. All the paths are relative and it's causing them to all be incorrect. I did get the following in Terminal after building.

`Info: No 'siteRoot' is defined in 'static.config.js'. This is suggested for absolute url's and a sitemap.xml to be automatically generated.`

I'm just not sure what this means. I have the static.config.js file open, but I am unsure how/where to add the "siteRoot". Any help would be appreciated.

**Comment by tannerlinsley** [comment]
If you are hosting your site at a custom base path of a domain, you must set the `config.basePath` to something like `base/path`, or whatever your base path is. `siteRoot` as it says, is not required, but recommended.

**Comment by andywarren** [comment]
@tannerlinsley I did end up figuring it out. I found the API reference and was able to set these:

`siteRoot: 'https://sub.domain.com',
  basePath: 'static/react-static',`

Once I set those and ran the build again it worked great. Thanks for the quick reply!

**Comment by JoseFMP** [comment]
For me I have an issue in here.
If I set the basePath, everything works correctly except one thing. The content generated is not static.
Which is bad because that's the whole point of using `react-static`. Isn't it?
