### ISSUE TITLE
Basic install fails

### ISSUE THREAD

**Issue by timarney** [nozzle/react-static#26]
Tried starting a basic project

```bash
$ react-static start 
=> Copying public directory...
=> [✓] Public directory copied: 3.053ms
=> Building...
=> [✓] App serving at http://localhost:3000
Failed to rebuild.
```

**Errors**
./node_modules/react-proxy/modules/createPrototypeProxy.js
Module not found: Can't resolve 'lodash/assign'
Module not found: Can't resolve 'lodash/difference'
Module not found: Can't resolve 'lodash/find'

./src/App.js
Module not found: Can't resolve 'react-static-routes'
Module not found: Can't resolve 'lodash/difference'

**Notes**
I tried installing lodash - which fixed that error
I also tried react-static-routes - I looked at the package in the modules dir and it was just a package.json file

**Comment by tannerlinsley** [comment]
What node version are you using?

**Comment by timarney** [comment]
I’ll check the exact when I’m back but I think it’s 8.2.x

**Comment by Nembus** [comment]
Actually, it has to be Node >= 7.6 because the project uses async.

**Comment by tannerlinsley** [comment]
Yep, your totally right.

**Comment by tannerlinsley** [comment]
And yes, more info on that: `react-static-routes` is a generated dependency per build, located temporarily in the `dist` directory (which also serves as a node_modules resolution point under the hood). This is purely to avoid circular dependencies. :)

**Comment by Nembus** [comment]
But if you're forced to be on v6.x.x (say because of AWS Lambda limitation)?

**Comment by Nembus** [comment]
I’m willing to submit a Pull Request. For that do I need repo access rights
if not forking?


On October 11, 2017 at 11:06:28 AM, Tanner Linsley (notifications@github.com)
wrote:

And yes, more info on that: react-static-routes is a generated dependency
per build, located temporarily in the dist directory (which also serves as
a node_modules resolution point under the hood). This is purely to avoid
circular dependencies. :)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nozzle/react-static/issues/26#issuecomment-335842259>,
or mute the thread

**Comment by tannerlinsley** [comment]
Yeah, just fork, create a branch for the fix, then PR to this master.
