### ISSUE TITLE
storybook can't run because of the custom babel config. anyway to go around it?

### ISSUE THREAD

**Issue by adamchenwei** [nozzle/react-static#268]
```
ERROR in ./.storybook/addons.js
Module build failed: Error: [BABEL] C:\site\.storybook\addons.js: Couldn't resolve extends clause of C:\site\react-static\.babelrc in base
```
Running latest storybook and fairly recent react-static

I think it may because the custom babelrc setup?

```
{
  "extends": "react-static/.babelrc"
}

```

**Comment by hmeissner** [comment]
Hey @adamchenwei! Since some `.babelrc` configs seem to throw errors with `storybook`, it provides a nice way for you to separate the storybook babel config from your app.

All you have to do is to add a `.babelrc` file inside `.storybook` directory in your app. You can put storybook's config in there (code below) and everything should work just fine!
```javascript
{
  "presets": ["env", "stage-0", "react"],
  "plugins": [
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }]
  ]
}
```

**Comment by adamchenwei** [comment]
@hmeissner thanks! let me try that out tonight! 👍

**Comment by tannerlinsley** [comment]
Hoping this worked, but closing for now. Reopen if needed!
