### ISSUE TITLE
how to change the loading icon?

### ISSUE THREAD

**Issue by adamchenwei** [nozzle/react-static#295]
![image](https://user-images.githubusercontent.com/4201698/34902142-62c6eafe-f7e3-11e7-8a27-64abb767e514.png)

I would love if there is a direct way I can replace the icon and its placement? right now its on the top of the screen. 

I do see it seems only for dev env
![image](https://user-images.githubusercontent.com/4201698/34902150-a1e5397a-f7e3-11e7-979d-6568e4c0cce5.png)
if that's the case, what is the best approach to place a loading icon just like react static did but since we are outside react-static, we can't do the same, right?

Thanks!

**Comment by tannerlinsley** [comment]
The loading indicator is only visible in dev mode. Right?

**Comment by adamchenwei** [comment]
@tannerlinsley well, that's seem how it is in the code, I did not verify. but would love to know how to do the loading icon in prod, and how to resolve conflict with dev version loading icon in this case....

**Comment by tannerlinsley** [comment]
A loading icon can be achieved in Prod by subscribing to the loading state on the `Router` component (https://github.com/nozzle/react-static#router):

> To Subscribe to Router loading events, use Router.subscribe(callback). This can be extremely useful when using a library like nprogress to show a loading status. The subscribe callback will fire whenever the loading state changes:
```javascript
import { Router } from 'react-static'

Router.subscribe(loading => {
  if (loading) {
    console.log('A page is loading!')
  } else {
    console.log('A page is done loading!')
  }
})
```

Using this api, you can use any loading component or library you want (I suggest https://github.com/rstacruz/nprogress). Note though, that you are responsible for maintaining the state of the loading on your own, since the subscription is simply a notification of the changes to the loading state.
