### ISSUE TITLE
Pass data to static.config.js

### ISSUE THREAD

**Issue by ComputerCarl** [nozzle/react-static#303]
Is there a way to pass arguments into the `static.config.js` file?

For example, in the top component I have parameters  and functions defined which I would like passed down to the `react-static` generated routes ;
`<Routes thing={true} />`

 `static.config.js`  file;
````js
export default ((infoPassedToMe) => { return {
  getSiteProps: () => ({
    title: 'React Static',
    myThing: infoPassedToMe.thing
  }),
...
})()
````

**Comment by tannerlinsley** [comment]
Currently no. Any data used in the static.config.js file needs to either be
- an environment variable
- synchronous data imported from another file
- asynchronously fetched data in the getSiteProps or getRouteProps

**Comment by ComputerCarl** [comment]
Thanks.. i did initially import a settings file into both the highest App component and `static.config.js`.. but it didn't seemed like I was fudging it.

Is this something you plan on implementing? I updated the pseudo-code to include a non-breaking self-executing anonymous function.

I am enthusiastically trying to master this and use it for a portion of a fairly complicated app;

**Comment by lottamus** [comment]
@ComputerCarl how is that different than doing something like this?

```
import infoPassedToMe from './index.js'

export default {
  getSiteProps: () => ({
    title: 'React Static',
    myThing: infoPassedToMe.thing
  }),
}
```

**Comment by BeheadedKamikaze** [comment]
The important thing to understand is that this configuration is **static**. It runs only once, at build time. In your hypothetical example, where would the parameter originate? When could its value change?

As @lottamus has suggested, if the information is static or shared you can import it from a shared file. Otherwise if it's dynamic, you're probably well off just defining a function somewhere that can work out whatever `myThing` is based on `infoPassedToMe` - perhaps think of it like a library or a service.

Or if it's some shared state that will be initialised when the application starts (or any time after that), maybe a library like Redux would solve your problem?

**Comment by ComputerCarl** [comment]
@lottamus it is a fairly minor thing; I just would have rather kept it in the higher component.

@BeheadedKamikaze I'm probably having a little trouble separating the static and the dynamic portions of the app. I will move the logic further downstream for the portions I need to be dynamic and try not to pollute the `react-static` configuration and routes.
