### ISSUE TITLE
one more example

### ISSUE THREAD

**Issue by inventanew** [nozzle/react-static#319]
I love react static, If anyone could make a netlifycms starter with a framework like bulma or bootstrap that would help us newbies tremendously. Thanks for all the hard work, trying to wrap my head around all this to make a site.

**Comment by killvung** [comment]
At least for integrating with bootstrap library, not sure how other people do it, but for me. I included the needed html tags for bootstrap under Document in static.config.js, so that the static page would include to reference to bootstrap library when built 

![screen shot 2018-01-28 at 8 53 18 pm](https://user-images.githubusercontent.com/7685886/35491641-53e7b446-046d-11e8-9ca0-ddd1f12f56fd.png)

**Comment by inventanew** [comment]
Thanks for the response! I'll try it out

**Comment by tannerlinsley** [comment]
We'll keep this in mind. Thanks for the suggestion!
