### ISSUE TITLE
service work integration 

### ISSUE THREAD

**Issue by killvung** [nozzle/react-static#320]
Has anyone tried integrating service worker to their react-static application and would like to share out as a template?

**Comment by tannerlinsley** [comment]
We're working on a solution to this, but it will be a few weeks at least before we have a decent idea of how to solve this.  Service workers are tricky to get right for an 80% use case, so it's much safer to implement your own.  AFAIK, you could use just about any tutorial to build your service worker you want. Since it's just javascript, there is nothing special yet to integrate it with React Static.

**Comment by killvung** [comment]
yea! Finally

**Comment by rileylnapier** [comment]
theres also some nice webpack service worker plugins that make things pretty easy

**Comment by maduraPradeep** [comment]
I have tried workbox-webpack plugin but not succeeded. Then I have used Workbox CLI and added script to build target. IT WORKED.

https://developers.google.com/web/tools/workbox/modules/workbox-cli

"build": "react-static build --verbose && workbox generateSW",
