### ISSUE TITLE
if I have a static page make with react-static, can I make the static web to dynamic

### ISSUE THREAD

**Issue by kavanLi** [nozzle/react-static#433]
1. if I have a static page make with react-static or gatsby, I want to add something dynatmic a few month later. Can I make the web to dynamic, in other words, to write some javascript or jQuery to add eventListner or ajax request?And Is that react-static or gatsby can integrate with react to solve this problem?

2. Is that gatsby can't biuld with SEO?

3.
![image](https://user-images.githubusercontent.com/33696428/37008029-2de11f4c-211b-11e8-8b84-5091879b6cf5.png)
![image](https://user-images.githubusercontent.com/33696428/37008032-30dcbed6-211b-11e8-8833-725abfdf608c.png)
I need to develop a static website like the above image, this static web may have 15 pages. Can I use react-static or gatsby to make it out? And whick one is best? or those things are not good, just use html + bootstrap to achive the goal?

These is my question? Can anyone familiar to static web can answer me? Thanks in Advanced.

**Comment by tannerlinsley** [comment]
You can do all of those things with React Static or Gatsby. Which one you choose is up to you. I would recommend starting with the `basic` example from React-Static. Follow the quick start steps in the Readme to get started :)

**Comment by tannerlinsley** [comment]
You can also join the Slack organization to get more help :)

**Comment by mjsisley** [comment]
1. You have a lot of flexibility with react-static. You can add dynamic stuff at any time. I think you misinterpret what "static/dynamic" mean in this context though... dynamic refers to content that can only be decided at runtime, instead of build time (which is "static"). User interactions defined in JS is still "static". 

You can write JS interaction with whatever libs you want while using react-static (though using jQuery in a react app is definitely not recommended... you should take an approach more in line with React).

2. Gatsby generates static content just like react-static. Static content is ideal for SEO.

3. react-static and Gatsby are both good for anything (and make future improvements/ highly interactive interfaces) easier. However, if your scope is very limited and you don't anticipate needing a lot of interaction, then html/bootstrap should work fine and using a react based tool (when you aren't familiar with react or the ecosystem) may be overkill.

Comparing Gatsby/react-static
Gatsby is more opinionated (AKA, it would be easier to migrate a react-static site to some other setup like CRA than it would be to migrate a Gatsby site). Read https://medium.com/@tannerlinsley/%EF%B8%8F-introducing-react-static-a-progressive-static-site-framework-for-react-3470d2a51ebc for react-static's take for a more detailed comparison.

**Comment by kavanLi** [comment]
thank you
