### ISSUE TITLE
Paths with trailing slash are not working in development

### ISSUE THREAD

**Issue by denis-sokolov** [nozzle/react-static#496]
When I define a path with a trailing slash in the static config, it still shows up without the trailing slash in development. In production, however, due to #494, they do show up with the trailing slash, so even if we did not plan to support this, we may want to decide to start.

```js
{
    path: "/about/",
    component: "src/About"
},
```

Edit: Noticed this is a duplicate of #176, which was closed without comment.

**Comment by tannerlinsley** [comment]
Yeah, we should probably start supporting this. There's a lot to cover here though:
- All paths are cleaned going into RS so they can reliably be joined together. This happens everywhere, so we would need to be extremely thorough with this change.
- React-Router would need to respect this changes as well
- What happens when a user types in `/about` in the address bar?

**Comment by denis-sokolov** [comment]
Yes, the amount of work and breakage in this issue is considerable.

Today when a user types in `/about`, the server most likely redirects them to `/about/` (#494), which them is hydrated on the client without changing the path. If a user then clicks on “Home” and “About”, they end up on `/about`, routed client-side.

**Comment by bernatfortet** [comment]
Still happening to me. with 5.7.5

@denis-sokolov @tannerlinsley  is there anyway to work around this in the meantime?
I love react-static but if I can't get links to work the website is not usable

**Comment by tannerlinsley** [comment]
In the basic example of the app, I am not seeing any server or build problems with any of the following configurations:

No trailing slash:
```javascript
{
        path: '/about',
        component: 'src/containers/About'
      }
```
with both: 
```javascript
<Link to="/about">About</Link>
// or
<Link to="/about/">About</Link>
```

or

Trailing slash:
```javascript
{
        path: '/about/',
        component: 'src/containers/About'
      }
```
with both: 
```javascript
<Link to="/about">About</Link>
// or
<Link to="/about/">About</Link>
```

**Comment by bernatfortet** [comment]
I have to double check but I commented siteRoot out and it works for me now

**Comment by FullstackJack** [comment]
I am also having trouble loading routes on `yarn serve` and Netlify. When it goes to `/blog`, it reloads to `/blog/` and even though it began to show the page at `/blog`, `/blog/` quickly replaces with 404 due to the redirect. In effect, deep linking is not working and the site can't be used or deployed for production use.

**Comment by FullstackJack** [comment]
Ok, I figured out my issue. There was an `Unexpected Identifier` error in my console for development builds. It turns out I am writing blog posts with Markdown and in the YAML front matter, I had written a date but it didn't get wrapped in quotes during compilation. I think I might switch to using JSON front matter to be more explicit from now on. Now the trailing slashes work properly. I was banging my head against the wall trying to solve this.
