### ISSUE TITLE
[Q] How I can remove window.__routeInfo from generated HTML files?

### ISSUE THREAD

**Issue by dehghani-mehdi** [nozzle/react-static#514]
Hi,

It seems like extra and useless peace of data in final HTML, and it should be removed (I prefer to cut that off), so is there any way to do that?

BTW, during creating new site please add progress bar or something.

Thanks.

**Comment by tannerlinsley** [comment]
You should never remove `window.__routeInfo` from the final html. It is there for a purpose: to ensure that any page, when used as an entry point, can synchronously bootstrap react without making asynchronous calls. If you remove this data, you will be forfeiting the benefits of React-Static.

As for the progress bar, unfortunately it is out of our control. `yarn` and `npm` both run an install when a project is created. Yarn has a pretty good progress bar, so maybe you should use that. It is automatically detected which to use on your machine.

**Comment by dehghani-mehdi** [comment]
In the docs you mentioned that React-Static is SEO ready, but as far as I know this extra texts is not good for SEO, and because of that I can't use React-Static.

_Too soon for closing the issue btw._

**Comment by derekperkins** [comment]
@dehghani-mehdi The extra routeInfo will not impact your SEO in any significant way.

**Comment by dehghani-mehdi** [comment]
I'm sorry, but I'm not agree with you.

The extra info add extra (unnecessary) text to the page (by unnecessary I mean the extra info is not part of actual page content), so more size, more words, in some cases duplicate unnecessary words.

**Comment by tannerlinsley** [comment]
You are not understanding the reasons for the data being embedded. It is
there to ensure that react can bootstrap synchronously over the HTML
without flashing a loading or blank screen. If it were removed, you would
see the full content of the page, then a flash where the content
disappears, then after a second or two, the content would reappear again.
This is a terrible user experience, and would absolutely have more of a
negative impact on your SEO than having the extra bytes of json in your
HTML. Again. It's there for a reason. You are more than welcome to fork
this repo and remove it if you don't agree.

**Comment by dehghani-mehdi** [comment]
Thanks for the explanation, I know you are adding that info for a reason and the page/code will be broken (as you mentioned) without them, I'm looking for some other solution, I don't know, maybe inject that data using JS. static sites are light enough and refreshing the page (on navigate) not a big deal. of course adding that ability will be great, but using JS.

And seems like React-Static looks terrible if user disable JS in his/her browser (based on your answer).

**Comment by freshtonic** [comment]
> And seems like React-Static looks terrible if user disable JS in his/her browser (based on your answer).

@dehghani-mehdi it seems that you think that the JS `window.__routeInfo` data embedded in the page is required for the initial page load. The static page will render fine without it, but it _is required to bootstrap your react app *to precisely replace the static content*. If JS was disabled your users would still see the statically rendered version of your page.

**Comment by tannerlinsley** [comment]
@ freshtonic That is correct. With JS disabled, everything will function correctly. @dehghani-mehdi, I understand what you are saying, but what you are suggesting would incur even more cost into a page load performance than currently. Using JS to fetch the embedded data would mean a few things:
- React would bootstrap slower, putting your perceived page performance (interactivity) at a disadvantage, since you have to wait for data to download before you can mount anything.
- Because of the above, code you would expect to run ASAP in your react app would not, thus you would not have the same speed of response as you do now.
- Adding embedded JS into the HTML is the perfect tradeoff for React-Static's purposes.
- The performance improvements for this hypothetical change would be negligible at best. 

Again these are just my best guess. If you believe you can rewrite the mounting logic to be faster, more seamless, and also do it with 100% backwards compatibility, then I again invite you to fork the repo and give it your best shot.
