### ISSUE TITLE
404 error on home page

### ISSUE THREAD

**Issue by jsamr** [nozzle/react-static#523]
This errors occurs since **5.6.3** (I cannot reproduce for **5.6.2**). I haven't tested in production, so I can only guarantee it happens in development. 

Relevant static config :

``` javascript
getRoutes: () => [
    {
      path: '/',
      component: 'src/pages/Home',
    },
]
```

So I'll stick to 5.6.2 waiting for a fix ! If you need a reproduction I might setup one, but please have a close look at 5.6.3 changes before 44b390a2b4420d8cdd633cc2ccf584a473090458 commit since it should be hidden somewhere here.

**Comment by mihai-tatar** [comment]
It looks like this was introduced in `https://github.com/nozzle/react-static/commit/435f8b3338158167b04288273ad92066b9b4d6d7`, because it attempts to dereference the result of `decodeURIComponent ` to an object, while the result is actually a string.

I'll open a pull request on this in a short while.

**Comment by tannerlinsley** [comment]
Fixed in latest version.
