### ISSUE TITLE
Build Error: write EPIPE

### ISSUE THREAD

**Issue by mhjey** [nozzle/react-static#741]
### Environment

1.  `react-static -v`: **5.9.7**
2.  `node -v`: **v8.11.1**
3.  `yarn --version or npm -v`: **1.9.4**
4.  Operating system: **macOS High Sierra 10.13.6**

**Problem:**

My Build fails with following error: 

```
=> [✓] Routes Built: 25376.146ms
=> Bundling App...
=> [✓] App Bundled: 17964.750ms
=> Fetching Site Data...
=> [✓] Site Data Downloaded: 0.078ms
=> Fetching Route Data...
=> [====] 1032/1032 100% 33290/s 0.0s
=> [✓] Route Data Downloaded: 36.247ms
=> Exporting Route Data...
=> [✓] Route Data Exported: 27.565ms
=> Exporting Shared Route Data...
=> Exporting HTML...
=> [=] 1/1 100% Infinity/s 0.0s
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1022:11)
```

I think the problem is, that I try to build 1032 routes. Because it didn't fail before when I build less routes. How can I fix this, since I need to build all these routes?

**Comment by tannerlinsley** [comment]
This could be one of the following:
- A process ran out of memory
- A disk ran out of space
- Something totally random

Either way, I don't know how to properly diagnose this. I would suggest removing routes from your config and incrementally adding them back in until you experience the error. This will give you a better idea of what's going on.

You could also share the repo with us (because without it, we cannot replicate the problem ourselves, and thus cannot fix it). 

Reopen with more info or a link to a repo where we can replicate the issue.
