### ISSUE TITLE
Hot reloading doesn't work in a fresh stable install

### ISSUE THREAD

**Issue by dontmakemethink** [nozzle/react-static#803]
**Describe the bug**
Hot reloading doesn't work in container components.

The version of `react-static` is `^5.9.12`.

**To Reproduce**
1. Create a new project using `react-static create` command with a `basic` template.
2. Start the dev server with `yarn start`
3. Change some text in a container component such as `About.js` - the changes are not reflected in the browser

**Desktop (please complete the following information):**
 - OS:  macOS High Sierra 10.13.6
 - Browser: chrome nightly

**Comment by Pixelatex** [comment]
This has been fixed in https://github.com/nozzle/react-static/pull/748 but I don't think it has been included in the latest release yet. (fix was 4 days ago, release 6 days)

Adding plugins": ["react-hot-loader/babel"] to your babel.rc should fix your issue.

p.s. @tannerlinsley maybe do a new release with this included?

**Comment by dontmakemethink** [comment]
Indeed, it fixed the issue! I really appreciate your help :)

I think it'd be nice to have it "out of the box" 😅

**Comment by Pixelatex** [comment]
@dontmakemethink next release should have it :)

**Comment by Pixelatex** [comment]
Closing this issue as the bug has been fixed for you + permanent fix is on it's way.
