### ISSUE TITLE
CLI Error: react-static-create(1) does not exist

### ISSUE THREAD

**Issue by f2net** [nozzle/react-static#807]
**Describe the bug**
The CLI command

`react-static create`

shows an error.

**To Reproduce**
I just installed react-static globally using 

`yarn global add react-static` (latest version of yarn 1.10.1) 

If I launch

`react-static create`

I receive the error
`error: react-static-create(1) does not exist, try --help`

The help command is the only which works.

I'm using Node 10.9.0 on a Mac with MacOS Sierra 10.12.6.

I fear it's a problem with my environment, but other CLIs like create-react-app, gatsby or next work well.

Thank you,
Matteo

**Comment by f2net** [comment]
If I uninstall the global package with yarn and reinstall it with npm it's worst, because I see the package installed doing a

`npm ls -g --depth 0`

but if I run 

`react-static`

it doesn't find the command.

**Comment by f2net** [comment]
I tried cleaning the yarn cache and reinstalling, but I receive the same error as before:

`error: react-static-create(1) does not exist, try --help`

**Comment by Pixelatex** [comment]
This sounds a lot like:

https://github.com/nozzle/react-static/issues/789

**Comment by f2net** [comment]
Yes, thank you for pointing me.
Unfortunately for me npm (tried with 6.2.0 and 6.4.1) gives a worst result than yarn:

`-bash: /usr/local/bin/react-static: No such file or directory`

**Comment by f2net** [comment]
Ok, I confirm that it is a problem with yarn 10.x and also npm...
I uninstalled the react-static from npm, downgraded yarn to 1.9.4, installed from yarn and now it executes.

**Comment by Pixelatex** [comment]
I'll see if I can replicate the issue so we can know if it is caused by yarn/npm or some weird issue in our setup.

**Comment by Pixelatex** [comment]
Am unable to reconfirm this bug with npm or yarn so far... I'll try on my work computer tomorrow but I'm afraid it seems to env-specific.

**Comment by enscripter** [comment]
I had the issue but seemed to be related to where bin was pointing with `yarn global bin` and `npm` being in different areas I was also using `nvm` to make matters even more confusing running `where react-static` and `where npm` helped me figure out things were pointing in all different directions.

**Comment by f2net** [comment]
Thank you, so I think it's a problem with my environment.
I keep yarn 1.9.4 until I have time to understand what is the problem with my env.

**Comment by stefanprobst** [comment]
I have the exact same problem. I have `react-static` in `~/.yarn/bin/` which is a symlink to `~/.config/yarn/global/node_modules/.bin/react-static` which again is a symlink to `~/.config/yarn/global/node_modules/react-static/bin/react-static`.

`commander` tries to locate `react-static-create` in `~/.config/yarn/global/node_modules/.bin/`
So it seems to me that `commander` (in `executeSubCommand`) fails to properly resolve all symlinks?

This is not a problem with yarn 1.9 because it directly links from `.yarn/bin/` to `.config/yarn/global/node_modules/react-static/bin/`.

Not sure who's to blame here?

**Comment by AubreyHewes** [comment]
I have the same problem.. I also have found a workaround/resolution

It seems that it is indeed due to the installed symlink pointing to a relative path that is breaking. If you execute the command directly it works... see workaround/solution below.

#### Environment
```bash
$ lsb_release -ds && uname -rv && node -v && yarn -v
Ubuntu 17.10
4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018
v8.12.0
1.12.3
```
#### Reproduce

##### Remove the global package

    yarn global remove react-static

##### Check it is no longer available

    which react-static

_Above should have no output_

##### Add the global package

    yarn global add react-static

##### Check it is now available

    which react-static

Above should have output pointing to something like `/home/X/.local/bin/react-static`

##### Try to create a project

    react-static create

_Above fails with_
````error: react-static-create(1) does not exist, try --help````

##### Check the command

    ls -lad $(which react-static)

_Above outputs something like_
````/home/X/.local/bin/react-static -> ../../.config/yarn/global/node_modules/.bin/react-static````

_Note the` ../../` in the symlink; it seems this is the problem_

##### Try using the command directly; so the command the symlink points to

    $(readlink -f $(which react-static)) create

The above works..

````
? What should we name this project? my-static-site

````

#### Workaround/Solution

Make the symlink absolute

    ln -fs $(readlink -f $(which react-static)) $(which react-static)
    ls -lad $(which react-static)

Outputs:
````/home/X/.local/bin/react-static -> /home/X/.config/yarn/global/node_modules/react-static/bin/react-static````

The symlink is now absolute and the command works ;-)

   react-static create

````
? What should we name this project? my-static-site

````

**Comment by luskin** [comment]
I'm having this issue as well, trying to switch from Gatsby to React-Static but can't even get a basic project off the ground. Anybody find a solution to this bug?

**Comment by AubreyHewes** [comment]
@luskin a useable (sic)  [workaround](https://github.com/nozzle/react-static/issues/807#issuecomment-438401891) is to make the symlink absolute

    ln -fs $(readlink -f $(which react-static)) $(which react-static)

Above works on linux based systems. osx, afaik, does not support `readlink -f` (out of the box) so in this case you would have to manually fix the `ls -lad $(which react-static)` symlink to the absolute path of the linked item.

Let me know if you get it working using this...

Note: on an update of `react-static` this would have to be repeated.

**Comment by MartinRosenberg** [comment]
@luskin And to make @AubreyHewes' workaround work on macOS, you have to first run
```bash
brew install coreutils
```
and then you can run the same command but with `greadlink` in place of `readlink`.

**Comment by dan-dr** [comment]
yeah why is this closed... still happening. thanks for the workaround @luskin

**Comment by Pixelatex** [comment]
This is not 100% reproducible and might be caused by your local setup.

**Comment by Pixelatex** [comment]
I tried to reproduce this on 4 separate devices. 2 of them who never had react-static on it. Tried it with both yarn & npm as well...

**Comment by MartinRosenberg** [comment]
The root of the problem appears to be with Yarn, and not React Static. Per https://github.com/yarnpkg/yarn/issues/648 (as mentioned in #789), Yarn has longstanding issues with global packages, such as installing to undesirable locations (particularly with nvm) and not linking. Reinstalling `react-static` with npm fixes the issue, or you can make the necessary adjustments for Yarn.

@Pixelatex, would you be willing to get fixes in for the [Quick Start](https://react-static.js.org/docs/#quick-start) docs with a warning about using `yarn global add`, and/or instructions for resolving the issue?
