### ISSUE TITLE
Conditional className is not properly updated in production

### ISSUE THREAD

**Issue by JohnBerlin** [nozzle/react-static#824]
## **Thanks for all your work, react-static is awesome!**

**Describe the bug**
While trying to store some state in localStorage, I've identified an issue with a conditional className for a component. While the state of the component is correct, it doesn't seem to update the className property as expected.

**To Reproduce**
1. Clone https://github.com/JohnBerlin/hydrate-does-not-work-on-classname
2. Run ```npm i```
3. Run ```npm run stage```
4. Run ```npm run serve```
5. Go to [http://localhost:3000](http://localhost:3000)
6. Click on one of the toggles
7. Reload the page
8. The text of the toggle is correct ("isOn" or "isOFF") but the style applied doesn't match the ".isON" CSS class

**Expected behavior**
The className property should be correctly updated once the page is loaded.

**Screenshots**
![screensghot](https://raw.githubusercontent.com/JohnBerlin/hydrate-does-not-work-on-classname/master/screenshot.png)

**Desktop (please complete the following information):**
 - OS: KUbuntu 18.04
 - Browser: Firefox & Chrome
 - Version: Latest

## **Thanks for all your work, react-static is awesome!**

Am I doing anything wrong with this?

**Comment by JohnBerlin** [comment]
Hey guys, any update on this? The issue is quite weird, could someone tell me if they're able to reproduce it?

**Comment by danjayrose** [comment]
I've also encountered this bug. I've found that a temporary fix is to retrieve the localstorage and set state in ComponentDidMount. Not ideal but it works.

**Comment by kevinmanncito** [comment]
Using a class based component + `componentDidMount` as a workaround isn't working for me on the latest version (7.0.10)

Here are two simple example components that don't work correctly. One is a functional component and one is a class based component. The content renders correctly but not the className.

```
export default class Home extends React.Component {
  state = {
    width: typeof window !== 'undefined' ? window.innerWidth : 1000
  }

  componentDidMount () {
    this.setState({
      width: window.innerWidth,
    })
    this.container.className = this.state.width < 500 ? 'mobile' : 'desktop'
  }

  render () {
    return (
      <div style={{ textAlign: 'center' }} className={`${this.state.width < 500 ? 'mobile' : 'desktop'}`} ref={container => { this.container = container }}>
        {this.state.width < 500
          ? (
            <h1>Welcome to React-Static - Mobile</h1>
          )
          : (
            <h1>Welcome to React-Static - Desktop</h1>
          )
        }
      </div>
    )
  }
}
```

and

```
export default () => {
  const width = typeof window !== 'undefined' ? window.innerWidth : 1000

  return (
    <div style={{ textAlign: 'center' }} className={`${width < 500 ? 'mobile' : 'desktop'}`}>
      {width < 500
        ? (
          <h1>Welcome to React-Static - Mobile</h1>
        )
        : (
          <h1>Welcome to React-Static - Desktop</h1>
        )
      }
    </div>
  )
}
```

**Comment by benadamstyles** [comment]
I am also getting this! So glad to have found your issue. It's up there with the weirdest things I've seen in a decade of software development. However, with much head-bashing/anger/grief/resignation, I have traced this down to what I *think* is expected React behaviour, explained [here in the React docs](https://reactjs.org/docs/react-dom.html#hydrate), raised [in a React issue too](https://github.com/facebook/react/issues/13260), and even on Stack Overflow where [this poor soul](https://stackoverflow.com/questions/51433193/class-name-hydration-mismatch-in-server-and-client-warning-prop-classname-d) lost most of 3 nights' sleep on it apparently!

The React docs [spell out what's going on with `hydration`](https://reactjs.org/docs/react-dom.html#hydrate):

> Unless it’s text content, React still won’t attempt to patch it up, so it may remain inconsistent until future updates.

In other words, when your JS gets evaluated in the browser and React Static calls `React.hydrate` to "revive" the static markup into a real React app, if anything comes out different than it did on the static build (i.e. on the "server"), and if it's a textual change, React will update it, but otherwise, it won't. So where, in our case, a `className` will be different in the browser than it was on the server, the only way to make React take that change and apply it is to actually make it different with a state update. It won't even update it with a `forceUpdate`. You literally have to **change** the `className`, otherwise React just won't update the DOM.

This has forced me to create and use the following hook, which you can repurpose if it helps you:

```js
export const useOnHydrate = (fn) => {
  const [value, setValue] = React.useState();
  React.useEffect(() => setValue(fn()), []);
  return value;
};
```

It's basically a state wrapper for any function, which means that your function will run once (and only once) on mount. This basically forces React to re-render whatever component has this hook in it *after* `hydrate`. It has solved the problem for me and maybe it will for you.

@tannerlinsley is it worth documenting this and perhaps even providing it as a utility hook? If so, I'm happy to do that work.

**Comment by SleeplessByte** [comment]
Hi Ben,

Tanner is no longer around; you may write this up, but in reality, code like Kevin posted is problematic to begin with. If you really _can't_ use media queries, you should run that code in a `useEffect`, and hook on a "document on size change" handler. That will resolve the issue to begin with -- regardless of hydration, SSR, or what's not.
