### ISSUE TITLE
NODE_ENV forced to `development`

### ISSUE THREAD

**Issue by mt-micky** [nozzle/react-static#857]
**Describe the bug**
I'm using `convict` and grab the set `NODE_ENV` or default to `develop` for CI purpose.
But since `react-static` set `process.env.NODE_ENV` to `development` I cannot get my default value when running `start`.

**Expected behavior**
Leave `process.env.NODE_ENV` alone. As a library, you shouldn't have to set a value yourself.

**Comment by Pixelatex** [comment]
Hey @mt-micky 

Ok, so it was supposed to have been changed in version 4.5.0 so you can use NODE_ENV for your own purposes. However.

Running start triggers this code, so it might be that your NODE_ENV variable hasn't been set yet when you run the start command? (might want to it to your package start script to prevent this from triggering)

```
  if (typeof process.env.NODE_ENV === 'undefined') {
    process.env.NODE_ENV = 'development'
  }
```

Otherwise there is no code setting NODE_ENV to `development` anywhere.

**Comment by mt-micky** [comment]
Yes. That code is my problem.
My system set the NODE_ENV to ’develop’ when not defined.
But since you define it first, it screws my app for development.
I shouldn't have to define it another place, just because you set it.
Why do you even need to set it to ’development’?

**Comment by Pixelatex** [comment]
This code will set it to development when it's NOT defined. Despite the fact on wether or not this is still used. (I think for webpack config maybe, @tannerlinsley confirmation?)

You can easily fix this issue by setting the node_env to the env you want before running start

**Comment by mt-micky** [comment]
But I shouldn't have to.

**Comment by mt-micky** [comment]
I'm pointing a problem.
I'm not looking for advice.

**Comment by tannerlinsley** [comment]
Many libraries (including React itself and Webpack) rely on the `NODE_ENV` variable to be set to `production` or `development` for proper inclusion/exclusion of code, minification, and performance reasons.

If you look at any near zero-config build system in the ecosystem, it is very normal for them to set this variable when none is provided. You will rarely see anyone run

```
NODE_ENV=development react-scripts start
```

Instead, you see this:

```
react-scripts start
```

This is because the `start` command is a development command and it would be redundant to require the environment as a prefix.

React Static is no different, it will never require the user to define an environment out of the box. They can easily be implied by the command the user is running.

With that said, I have still made it possible to set the `NODE_ENV` variable to whatever you want **as long as you do it before you run react-static commands**

If this still doesn't work for you, then it likely means you're setting and relying on `NODE_ENV` in a way that conflicts with the many many libraries that use it. I would then recommend you create and use your own environment variable like `MY_ENV=develop` and leave `NODE_ENV` alone.

To restate, if you are ever setting `NODE_ENV` to something other than `production`, `development`, or `test`, then you will likely get unexpected results from a majority of libraries you use.

**Comment by mt-micky** [comment]
Your last statement sounds like it should be documented somewhere then.

**Comment by tannerlinsley** [comment]
Indeed it should. Would you like to submit a PR to the docs for it?
