### ISSUE TITLE
React-static loader is shown in prod build/root page is initially shown

### ISSUE THREAD

**Issue by bvanmastrigt** [nozzle/react-static#957]
React-static loader is shown in prod build/root page is initially shown.

### Environment

1.  `react-static -V`: 6.1.5
2.  `node -v`: v8.12.0 (upgrade to v11.6.0 did not help)
3.  `npm -v`: 6.4.1 (upgrade to 6.5.0 did not help)
4.  Operating system: Windows 10
5.  Browser and version (if relevant): Chrome Version 71.0.3578.98 (Official Build) (64-bit) or FireFox 64.0 (64-bit)

### Steps to Reproduce the problem

1.  react-static create: basic
2.  npm run build
3.  npm run serve
4. open http://localhost:3000 in Chrome or FireFox (did not try other browsers)
5. when reloading the home page there is not flashing
6. when reloading http://localhost:3000/about in Chrome the loader is shown and the home page html is shortly displayed and in FireFox the loader is not shown but only the home page html is shortly displayed
7. same for blog and all its posts

I have also upgrade all packages to the latetst version, with same result:

```
"dependencies": {
    "@reach/router": "1.2.1",
    "axios": "0.18.0",
    "react": "16.7.0",
    "react-dom": "16.7.0",
    "react-hot-loader": "4.6.3",
    "react-static": "6.2.0"
  }
```
### Expected Behavior

I would expect that a hard page refresh (ctrl + shift + r) should initially show the correct rendered static page and that there should be no visible differences

### Reproducible Demo

It can be quickly reproduced by using the react-static cli (i hope :-))

**Comment by bvanmastrigt** [comment]
A small video demonstrating the issue: [https://file.io/XKnxJs](url)

**Comment by bvanmastrigt** [comment]
Video demonstrating the issue (available for 24 hours): [https://a.uguu.se/3BDHkKGISXmI.mp4](https://a.uguu.se/3BDHkKGISXmI.mp4)

**Comment by tannerlinsley** [comment]
This is actually OK. It's due to the way the `serve` package is set up in the template which is catered towards dynamic route testing on local builds. We have set it up to use the `-s` argument, which treats the site like a single page application, directing all routes to `index.html`. This is useful for developing dynamic routes. 

This is not the way it behaves on most servers, unfortunately. If you would like a more accurate representation of how things will behave, run `serve dist -p 3000` without the `-s` argument. But, keep in mind, dynamic routes might not work locally when you do this.

**Comment by bvanmastrigt** [comment]
Thank you for the clarification! I have manged to get the site running with react-static v6 :-)
