### ISSUE TITLE
Dynamic URLs don't use `basePath` correctly

### ISSUE THREAD

**Issue by JamesMessinger** [nozzle/react-static#975]
### Are you reporting a bug?
Yes

The `basePath` (and `stagingBasePath` and `devBasePath`) works fine for the static URLs that are generated in .html files, but URLs that are dynamically created via JavaScript don't use `basePath` correctly.  Sometimes they leave it off altogether.  Other times they repeat it **twice**.  

Related (but different) issues:
  - Issue #926 
  - Issue #972 

### Environment
1.  `react-static -V`: 6.2.0
2.  `node -v`:  10.11.0
3.  `npm -v`:  6.4.1
4.  Operating system:  Windows 10
5.  Browser and version (if relevant):  Chrome 71

### Steps to Reproduce the problem
1. Create a new project using the "basic" template

2. Add the following to the `static.config.json`

```
  basePath: "PRODUCTION",
  stagingBasePath: "STAGING",
  devBasePath: "DEV",
```

3. Run the dev server (`npm start`) and see that everything works correctly 
  - (although it's served from `/` not `/DEV` see Issue #972)

4. Do a staging build (`npm run stage`)

5. Move the contents of the `dist` folder to `dist/STAGING` to match our site config

```bash
mv dist STAGING
mkdir dist
mv STAGING dist/STAGING
```

6. Remove the `-s` option from the `serve` script in `package.json`.  That option causes problems due to the 404 issue that I'm demonstrating here.

7. Run the static server (`npm run serve`)
  - The site is served from `/STAGING` and **not** from `/`. This is good because it accurately tests whether our site will work correctly in a non-root directory.  :+1:

8. Open your browser dev tools and look at the "Network" tab.  
  - Try to browse to a few different pages of the site.  You'll see a lot of 404 errors.

  - All the URLs in the .html files are correctly prefixed with `/STAGING` and work correctly

  - URLs that are loaded dynamically via JavaScript are mostly broken.
    - Some are missing the base path (e.g. `/templates/src-pages-404.xxxxx.js`) 

    - Some have the base path **twice** (e.g. `/STAGING/STAGING/about/routeinfo.json`)

**Comment by JamesMessinger** [comment]
@tannerlinsley - I know that I appeared out of nowhere a couple days ago and started opening issues left and right, all related to `basePath` functionality.  Please don't get the impression that I'm just a complainer.  I think you're doing **great** work here, and I'm really excited about the direction of this project.   I just need it to work well in a non-root path, because that's my particular use case.  😊

I am more than happy to pitch-in and help fix these issues.  I'm just a bit unfamiliar with how all the moving pieces interact with each other, so I would need your guidance as to where to start looking.  I'd love to deep-dive into the code this weekend and hopefully send you a PR.

**Comment by tannerlinsley** [comment]
Thanks @JamesMessinger 😄. I would love for you to dive in and help us make this experience better. Clearly this is a very important feature and experience to support and it sounds like your use-case is a great testing ground to accomplish it. Let me know what I can do to help you help React Static 🎉

**Comment by tannerlinsley** [comment]
The first place I would suggest starting is in the `getConfig.js` file, where the config defaults, user config and computed config values all come together. From there you can do a project wide search on the variables you find interesting. If you have questions about a variable, I can help show you where it is created and why it's used where it is. One of the more interesting things to note is that many of the variables are placed on `process.env.REACT_STATIC_SOMETHING` so that they can be picked up on the client side during webpack bundling.

**Comment by tannerlinsley** [comment]
I noticed 😄. You rock man. Keep at it. You're use case and context is exactly what we need right now.

**Comment by DDunc** [comment]
@tannerlinsley, Please reopen when you get the chance, thanks! 

We're also experiencing this issue and seemingly-related `basePath` bugs with both React-Static 5.9.12 and 6.x. I'm a huge fan of react-static, I've migrated projects from other SSR libraries and it's been a great experience overall, but unfortunately this is a showstopping blocker. I really appreciate all the work you've done though, using React-Static has been like a breath of fresh air!

I'd like to help out as well and I'll take the information above as a jumping off point for my own attempts to root cause this cluster of issues. In terms of branch(es) to work against, is `master` the preferred branch or could it also be worthwhile to look at `v5` and `v7`?

**Comment by tannerlinsley** [comment]
Master is up to date for v6 so use that one! Thanks for your willingness to
help!

**Comment by JDvorak** [comment]
I'm also experiencing problems with this issue. Who has made the most progress here?
