### ISSUE TITLE
TypeScript error: JSX element type RouteData does not have any construct or call signatures

### ISSUE THREAD

**Issue by sw-yx** [nozzle/react-static#988]
### Are you reporting a bug?
Yes

### Environment

1.  `react-static -V`: 6.2
2.  `node -v`:11
3.  `npm -v`:6.4
4.  Operating system: mac osx
5.  Browser and version (if relevant): n/a

### Steps to Reproduce the problem

this line seems to not be valid? https://github.com/nozzle/react-static/blob/ca72862e96956ddf31a34d551bc45a44f0c8cbff/packages/react-static/src/index.d.ts#L35

when i try to use the RouteData component i get

```
[ts] JSX element type 'RouteData' does not have any construct or call signatures. [2604]
(alias) const RouteData: React.Component<{}, {}, any>
import RouteData
```

### Expected Behavior
 
no type error

### Reproducible Demo

one is here: https://github.com/sw-yx/react-static-podcast-hosting/tree/RouteDataIssue specifically i tried to use RouteData here https://github.com/sw-yx/react-static-podcast-hosting/blob/RouteDataIssue/src/pages/episode.tsx#L54

**Comment by devuxer** [comment]
I'm getting the same error, except it's `[ts] JSX element type 'Comp' does not have any construct or call signatures. [2604]`.

I literally just followed the instructions in the quick start and chose the TypeScript template.

**Comment by Balvajs** [comment]
I don't use react-static anymore, so I don't maintain the types. It's probably outdated.
You should fix the types and create pull request, if you need this to be fixed.

**Comment by sw-yx** [comment]
@devuxer this is the sort of thing we'll have to pitch in to help maintain if we want TS in RS to be a thing. i'm willing to look at it but am absolutely busy this week. thanks Balvajs for being responsive!

**Comment by devuxer** [comment]
@sw-yx, Before yesterday, I had never tried a React static site generator before, so I'm just in the phase of determining whether I prefer Gatsby or RS. I decided to check out RS first because it seemed more minimalist, but I was concerned about it not being polished/mature enough. Unfortunately, my experience with the TS starter not working didn't do much to ease my concern. This could just be a small hurdle and not representative of the project as a whole, but I'm afraid I'm not ready at this time to commit to contributing. That said, many thanks for moving the TS story forward, and I'm definitely not closing the door on contributing in the future--I just want to be able to experience what RS is all about before I invest time into improving it.

**Comment by sw-yx** [comment]
fair enough

**Comment by digitalkaoz** [comment]
i guess the right syntax would be:

```tsx
  const render = (Comp: React.ReactType) => {
    renderMethod(<Comp />, document.getElementById("root"));
  };
```

**Comment by tannerlinsley** [comment]
Would easily accept any PRs to improve this experience. Thanks for your input guys!
